{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "ack-iam-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-iam-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-iam-controller.chart.name-version" . }}
  name: {{ include "ack-iam-controller.service-account.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
