apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/iam.services.k8s.aws_groups.yaml
  - bases/iam.services.k8s.aws_instanceprofiles.yaml
  - bases/iam.services.k8s.aws_openidconnectproviders.yaml
  - bases/iam.services.k8s.aws_policies.yaml
  - bases/iam.services.k8s.aws_roles.yaml
  - bases/iam.services.k8s.aws_servicelinkedroles.yaml
  - bases/iam.services.k8s.aws_users.yaml
